### ISSUE TITLE
how to use JZZ.SF2

### ISSUE THREAD

**Issue by tizi24** [jazz-soft/JZZ-midi-SF2#1]
This is great! how to use it to connect my midi controller?

**Comment by jazz-soft** [comment]
This module is not fully functional yet. Work in progress...

**Comment by tizi24** [comment]
> Este módulo aún no es completamente funcional. Trabajo en progreso...

This work is great!

**Comment by tizi24** [comment]
good.. check this is an implementation to use soundfonts with jzz midi? If so, it would have support for pitch bend and modulation, I'm looking for a way to be able to use pitch bend with some sf2 lib with jzz midi

**Comment by tizi24** [comment]
good.. check this is an implementation to use soundfonts with jzz midi? If so, it would have support for pitch bend and modulation, I'm looking for a way to be able to use pitch bend with some sf2 lib with jzz midi
